# Generated by Django 6.1 on 2026-08-14 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Email pochta')),
                ('date', models.DateField(verbose_name='Kelingan sana')),
                ('time', models.TimeField(verbose_name='Vaqt / Soat')),
                ('guests_count', models.IntegerField(verbose_name='Odamlar soni')),
                ('reason', models.CharField(choices=[('birthday', "Tug'ilgan kun"), ('romantic', 'Romantik kechki ovqat'), ('business', 'Biznes uchrashuv'), ('family', 'Oila bilan kechki ovqat'), ('other', 'Boshqa sabab')], default='other', max_length=50, verbose_name='Tashrif sababi')),
                ('special_request', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha istaklar")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
