# Generated by Django 6.1 on 2026-08-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.IntegerField(default=1, verbose_name='Odamlar soni'),
        ),
    ]
