"""
Django settings for final project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
import os


import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'neondb',
        'USER': 'neondb_owner',
        'PASSWORD': 'npg_snhOMy7e8HKu',
        'HOST': 'ep-proud-mode-ayitmowp.c-5.us-east-2.aws.neon.tech',
        'PORT': '5432',
    }
}




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tufnpt^#k&qo(=x!d%e0kpor4vk2u9++!(w_(*29cbfmq-o6c_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Hamma domenlardan kirishga ruxsat berish



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Aynan shu yerga qo'shing!
    'django.contrib.sessions.middleware.SessionMiddleware',
    # ... qolgan middlewarelar
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('uz', _('Oʻzbek')),
    ('ru', _('Русский')),
    ('en', _('English')),
    ('ja', _('日本語')),
]



TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/






STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WhiteNoise keshini yoqamiz (CSS tez yuklanishi uchun)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'





LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration



import os

# Resend bepul email tizimi sozlamalari (To'g'ridan-to'g'ri ulanish)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '://resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'  # Bu o'zgarmaydi, matn holida qoladi

# Maxfiy kalitni to'g'ridan-to'g'ri fayl ichiga yozamiz (Vercel o'qishi uchun)
EMAIL_HOST_PASSWORD = 're_PmrczSTG_KLvriYZEWbcrLngsN4y8GsKG' 

DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'  # Bepul jo'natuvchi nomi


# Resend Email sozlamasi
RESEND_API_KEY = 're_PmrczSTG_KLvriYZEWbcrLngsN4y8GsKG'

# Til sozlamalari
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 365 * 24 * 60 * 60  # Tilni 1 yilgacha eslab qoladi
LANGUAGE_COOKIE_PATH = '/'

